buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        if (providers.gradleProperty("playPublishing").map { it.isEmpty() || it.toBoolean() }.getOrElse(false)) {
            classpath "com.github.triplet.gradle:play-publisher:4.1.1"
        }
    }
}

plugins {
    id "com.android.application" version '9.4.0' apply false
}

apply from: "$rootDir/gradle/release.gradle"
