package vibro.navigator.nav.compass;

public enum CompassStreetType {
    MOTORWAY,
    MOTORWAY_LINK,
    TRUNK,
    TRUNK_LINK,
    PRIMARY,
    PRIMARY_LINK,
    SECONDARY,
    SECONDARY_LINK,
    TERTIARY,
    TERTIARY_LINK,
    UNCLASSIFIED,
    RESIDENTIAL,
    LIVING_STREET,
    SERVICE,
    TRACK,
    ROAD,
    BUSWAY,
    PEDESTRIAN,
    FOOTWAY,
    PATH,
    CYCLEWAY,
    BRIDLEWAY,
    STEPS,
    PLATFORM,
    CORRIDOR,
    REST_AREA,
    SERVICES,
    ELEVATOR,
    VIA_FERRATA,
    RACEWAY,
    OTHER
}
